name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  schedule:
    - cron: '0 9 * * *'

jobs:
  unit: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        npm install
        npm run all

  integration: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - core20
          - core22
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      id: snapcraft
      with:
        path: './test-projects/${{ matrix.project }}'
    - uses: actions/upload-artifact@v3
      with:
        name: 'snap'
        path: ${{ steps.snapcraft.outputs.snap}}

  integration-legacy: # make sure the action works on a clean machine without building
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        project:
          - core
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      id: snapcraft
      with:
        path: './test-projects/${{ matrix.project }}'
        snapcraft-channel: 4.x/stable
    - uses: actions/upload-artifact@v3
      with:
        name: 'snap'
        path: ${{ steps.snapcraft.outputs.snap}}

  check-runner: # make sure the action works on each VM image
    strategy:
      matrix:
        runner:
          - ubuntu-20.04
          - ubuntu-22.04
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        path: './test-projects/core22'
